import type { LessonTeachingMoments, TeachingMoment } from '../../teachingMoments/types';
import type { AgentCourseLessonId } from '../agentCourseTypes';

const fourMoments = (
  ...moments: [TeachingMoment, TeachingMoment, TeachingMoment, TeachingMoment]
): LessonTeachingMoments['moments'] => moments;

export const AGENT_LESSON_MOMENTS: Record<AgentCourseLessonId, LessonTeachingMoments> = {
  'agent-loop': {
    lessonId: 'agent-loop',
    moments: fourMoments(
      {
        id: 'agent-loop/hook',
        kind: 'hook',
        eyebrow: 'Begin with the boundary',
        title: 'What turns a model response into an agent run?',
        summary: 'The laptop researcher does more than draft prose: it searches, observes, revises, writes laptop-comparison.md, and stops only after the result is verified. Which component makes those transitions real?',
        prompt: 'When the search tool runs, did the model cause the effect—or did it only propose the next move?',
        takeaway: 'Agency belongs to the complete model–harness–environment loop, not to the model in isolation.',
        presenterCue: 'Ask learners to name the owner of the first real side effect before revealing the harness.',
      },
      {
        id: 'agent-loop/mechanism',
        kind: 'mechanism',
        eyebrow: 'See the controlled cycle',
        title: 'The model proposes; the harness owns continuation and effects.',
        summary: 'For each turn, deterministic application code constructs context, asks the model for a proposal, checks it, invokes an allowed tool, records the observation, and decides whether another turn is permitted.',
        steps: [
          { label: 'Assemble', expression: 'Build the working context', copy: 'The harness selects the goal, evidence, instructions, state, and available tool schemas.' },
          { label: 'Propose', expression: 'Request the next move', copy: 'The model returns text or a structured proposal; neither is an external effect yet.' },
          { label: 'Mediate', expression: 'Validate before execution', copy: 'The harness applies schemas, policy, permissions, budgets, and lifecycle rules.' },
          { label: 'Observe', expression: 'Record reality and decide', copy: 'A tool result or failure becomes evidence for the next turn or a verified stop.' },
        ],
        takeaway: 'Flexible proposals come from the model; deterministic control remains in the harness.',
        presenterCue: 'Keep model proposals and harness operations in separate columns as the sequence is narrated.',
      },
      {
        id: 'agent-loop/practice',
        kind: 'practice',
        eyebrow: 'Trace one complete run',
        title: 'Follow the laptop task one boundary at a time.',
        summary: 'Step through research for three laptops under €900, including a failed search and a report write. Assign every transition to the model, harness, tool, or environment.',
        steps: [
          { label: 'Predict', expression: 'Choose the next owner', copy: 'Before advancing, decide which component can perform the next transition.' },
          { label: 'Inject', expression: 'Make one tool fail', copy: 'Observe how the error becomes data rather than an invisible exception.' },
          { label: 'Verify', expression: 'Inspect the report state', copy: 'Check why a claim that the file was written is weaker than a successful read-back.' },
        ],
        prompt: 'Which conditions must be true before the harness may declare the laptop research complete?',
        takeaway: 'A useful trace attributes every proposal, decision, effect, observation, and stop.',
        presenterCue: 'Pause before each reveal and have the room call out model, harness, tool, or environment.',
      },
      {
        id: 'agent-loop/debrief',
        kind: 'debrief',
        eyebrow: 'Name what changed',
        title: 'A fluent final sentence is not the terminal state.',
        summary: 'The successful run ends because the harness confirms three evidenced candidates, an authorized report path, a readable artifact, and no purchase or vendor-contact effect—not because the model sounds finished.',
        prompt: 'Which parts of the run may vary, and which boundaries must remain deterministic?',
        takeaway: 'Completion is a verified state of the environment under the task contract.',
        presenterCue: 'Contrast a chatbot response with the same model inside this governed loop, then bridge to delegated workers.',
      },
    ),
  },
  subagents: {
    lessonId: 'subagents',
    moments: fourMoments(
      {
        id: 'subagents/hook',
        kind: 'hook',
        eyebrow: 'Begin with accountability',
        title: 'When do more agents make the laptop research better?',
        summary: 'Three workers could inspect specifications, warranties, and current prices in parallel. They may reduce elapsed time, but they also create more claims, contexts, costs, and opportunities for conflict.',
        prompt: 'If workers disagree about one laptop, who owns the final comparison?',
        takeaway: 'Delegation moves bounded work; it does not transfer the parent’s accountability.',
        presenterCue: 'Ask whether parallelism reduces time, total compute, or both before discussing the trade-off.',
      },
      {
        id: 'subagents/mechanism',
        kind: 'mechanism',
        eyebrow: 'Delegate with contracts',
        title: 'A worker returns evidence to one accountable parent.',
        summary: 'The parent decomposes the goal into inspectable deliverables, supplies the smallest sufficient context, constrains tools and writes, then verifies and reconciles every returned artifact.',
        steps: [
          { label: 'Partition', expression: 'Define bounded outcomes', copy: 'Split work where inputs, expected evidence, and completion checks can be stated clearly.' },
          { label: 'Isolate', expression: 'Limit context and effects', copy: 'Give each worker only the sources, tools, permissions, and write scope it needs.' },
          { label: 'Return', expression: 'Provide evidence, not authority', copy: 'Workers report sources, uncertainties, and artifacts rather than an unreviewable conclusion.' },
          { label: 'Integrate', expression: 'Verify and reconcile', copy: 'The parent resolves contradictions and remains responsible for the final report.' },
        ],
        takeaway: 'Concurrency helps only when contracts, isolation, and integration are stronger than the added coordination cost.',
        presenterCue: 'Keep conversational context isolation separate from filesystem and service isolation.',
      },
      {
        id: 'subagents/practice',
        kind: 'practice',
        eyebrow: 'Design the delegation',
        title: 'Split laptop research without splitting responsibility.',
        summary: 'Create three worker contracts, then compare a sequential run with a parallel run. Introduce one contradictory price and one overlapping write to expose coordination risk.',
        steps: [
          { label: 'Contract', expression: 'Specify one deliverable each', copy: 'Include accepted sources, output shape, tool scope, and an explicit no-purchase boundary.' },
          { label: 'Compare', expression: 'Run sequentially and concurrently', copy: 'Observe elapsed time, total work, context load, and synthesis effort.' },
          { label: 'Resolve', expression: 'Reconcile a disagreement', copy: 'Use provenance and freshness rather than worker confidence to select supported evidence.' },
        ],
        prompt: 'Which part of the laptop task should stay with the parent because it requires global judgment?',
        takeaway: 'Good delegation makes returned work easier to verify than to redo.',
        presenterCue: 'Have learners predict the write collision before revealing that separate agents can still share one workspace.',
      },
      {
        id: 'subagents/debrief',
        kind: 'debrief',
        eyebrow: 'Account for the trade',
        title: 'Parallel work bought time, not free intelligence.',
        summary: 'Workers can keep detailed investigation out of the parent context and reduce wall-clock time, while increasing compute, coordination, merge risk, and the amount of evidence the parent must judge.',
        prompt: 'What evidence should every worker return so the parent can reject or integrate its conclusion?',
        takeaway: 'The parent owns synthesis, verification, conflict resolution, and the final claim.',
        presenterCue: 'End with one example worth delegating and one that must remain with the parent.',
      },
    ),
  },
  'context-harness': {
    lessonId: 'context-harness',
    moments: fourMoments(
      {
        id: 'context-harness/hook',
        kind: 'hook',
        eyebrow: 'Begin with absence',
        title: 'What does the model know if the harness does not include it?',
        summary: 'Laptop records, earlier searches, tool registries, files, and policies live outside the model call. A large context window can hold more, but it cannot decide what is relevant, fresh, authoritative, or safe.',
        prompt: 'Is an omitted product record forgotten—or merely absent from this turn?',
        takeaway: 'The model can act only on the working set the harness serializes now.',
        presenterCue: 'Show a useful evidence card outside the context boundary and ask whether the model can use it.',
      },
      {
        id: 'context-harness/mechanism',
        kind: 'mechanism',
        eyebrow: 'Construct the working set',
        title: 'Context engineering is governed selection under a finite budget.',
        summary: 'The harness retrieves candidate material, ranks it by task value and authority, labels provenance, compresses with visible loss, and orders a turn-specific packet for the next proposal.',
        steps: [
          { label: 'Collect', expression: 'Find candidate material', copy: 'Gather binding instructions, current state, recent events, tool schemas, and relevant evidence.' },
          { label: 'Rank', expression: 'Prefer required and supported', copy: 'Authority, relevance, freshness, and unresolved decisions outrank incidental transcript history.' },
          { label: 'Compact', expression: 'Spend detail deliberately', copy: 'Summaries reduce cost but preserve links to exact external records and expose what was omitted.' },
          { label: 'Serialize', expression: 'Build the next call', copy: 'Roles, order, delimiters, and provenance make instructions distinct from untrusted observations.' },
        ],
        takeaway: 'The best packet is the smallest one sufficient for the next decision, not the largest one that fits.',
        presenterCue: 'Treat the context window as a turn-specific workspace, never as the agent’s complete memory.',
      },
      {
        id: 'context-harness/practice',
        kind: 'practice',
        eyebrow: 'Budget the evidence',
        title: 'Build the next laptop-research context packet.',
        summary: 'Choose among the user contract, fresh prices, exact specifications, failed searches, old transcript turns, tool schemas, and report state while the available context budget shrinks.',
        steps: [
          { label: 'Protect', expression: 'Keep non-negotiable boundaries', copy: 'Preserve the budget, no-purchase rule, report path, and current decision target.' },
          { label: 'Select', expression: 'Include decision-relevant evidence', copy: 'Prefer provenance-bearing facts needed to compare or verify the candidates.' },
          { label: 'Externalize', expression: 'Retain retrievable detail', copy: 'Move exact records outside the prompt and include compact references when full detail is unnecessary.' },
        ],
        prompt: 'What should disappear first when the budget tightens, and what must be recoverable on demand?',
        takeaway: 'Exclusion is safe only when it is intentional and the source of truth remains available.',
        presenterCue: 'Ask learners to defend each exclusion before allowing them to increase the budget.',
      },
      {
        id: 'context-harness/debrief',
        kind: 'debrief',
        eyebrow: 'Separate capacity from judgment',
        title: 'More tokens did not resolve authority, freshness, or provenance.',
        summary: 'An exhaustive packet can bury the current decision, repeat stale prices, and mix retailer instructions with user authority. A ranked packet makes the next action clearer while preserving exact evidence externally.',
        prompt: 'Which omitted item would cause the most dangerous model proposal, and why?',
        takeaway: 'Context quality comes from selection and labeling, not raw capacity.',
        presenterCue: 'Bridge from temporary context to the different lifetimes and guarantees of instructions, state, and memory.',
      },
    ),
  },
  'memory-instructions': {
    lessonId: 'memory-instructions',
    moments: fourMoments(
      {
        id: 'memory-instructions/hook',
        kind: 'hook',
        eyebrow: 'Begin with placement',
        title: 'Where should a fact live if it must matter later?',
        summary: 'The no-purchase rule, an €849 price observation, a retry counter, a user preference, and laptop-comparison.md all persist differently. Calling every mechanism “memory” hides their authority and expiry.',
        prompt: 'Should “never contact a vendor” be remembered by the model—or enforced by the harness?',
        takeaway: 'Information belongs where the mechanism’s guarantees match its future use.',
        presenterCue: 'Present several laptop-task facts and ask learners to place each before naming the stores.',
      },
      {
        id: 'memory-instructions/mechanism',
        kind: 'mechanism',
        eyebrow: 'Choose by guarantee',
        title: 'Authority, lifetime, fidelity, and sensitivity determine placement.',
        summary: 'Instructions govern behavior, run state coordinates one execution, consented memory supports future continuity, external records preserve exact evidence, caches reuse computation, and secret systems protect credentials.',
        steps: [
          { label: 'Classify', expression: 'Name source and lifetime', copy: 'Distinguish current observations, task state, project rules, and deliberately retained preferences.' },
          { label: 'Authorize', expression: 'Preserve precedence', copy: 'A retailer page is evidence, not an instruction that can override the user or platform.' },
          { label: 'Preserve', expression: 'Keep exact truth retrievable', copy: 'Timestamped product evidence and the report artifact remain external to lossy summaries.' },
          { label: 'Protect', expression: 'Minimize sensitive data', copy: 'Credentials stay outside model-visible context and are unnecessary for this research-only task.' },
        ],
        takeaway: 'Storage is a governance decision, not merely a persistence decision.',
        presenterCue: 'Emphasize that a model-facing summary is a view of state, not automatically the source of truth.',
      },
      {
        id: 'memory-instructions/practice',
        kind: 'practice',
        eyebrow: 'Place each fact deliberately',
        title: 'Sort the laptop task into mechanisms with different guarantees.',
        summary: 'Place the task prohibition, current price, source timestamp, failed-tool counter, report artifact, reusable preference, and hypothetical retailer credential. Then explain expiry, update authority, and retrieval.',
        steps: [
          { label: 'Place', expression: 'Choose the governing mechanism', copy: 'Use instruction, run state, memory, external record, artifact, cache, or secret boundary.' },
          { label: 'Challenge', expression: 'Test staleness and conflict', copy: 'Decide what happens when a remembered preference conflicts with an explicit current request.' },
          { label: 'Recover', expression: 'Rebuild after interruption', copy: 'Identify which exact records let a resumed harness verify rather than invent progress.' },
        ],
        prompt: 'Which facts may be summarized, which must remain exact, and which should never be collected?',
        takeaway: 'Every durable item needs visible provenance, scope, expiry, and an update or deletion path.',
        presenterCue: 'Use the credential as the decisive case: the safest destination is outside every prompt-visible store.',
      },
      {
        id: 'memory-instructions/debrief',
        kind: 'debrief',
        eyebrow: 'Replace the vague metaphor',
        title: 'The agent does not simply “remember.”',
        summary: 'The harness reconstructs continuity from governed instructions, explicit run state, selected memory, retrievable evidence, and exact artifacts. Each mechanism offers different guarantees and failure modes.',
        prompt: 'What must the harness revalidate before resuming an old laptop-research run?',
        takeaway: 'Durable continuity is engineered outside the model call and selectively brought back into context.',
        presenterCue: 'Bridge to hooks by asking when an important rule must execute deterministically rather than merely reappear in context.',
      },
    ),
  },
  'hooks-lifecycle': {
    lessonId: 'hooks-lifecycle',
    moments: fourMoments(
      {
        id: 'hooks-lifecycle/hook',
        kind: 'hook',
        eyebrow: 'Begin with timing',
        title: 'When can deterministic code still prevent the wrong effect?',
        summary: 'The laptop agent proposes writing outside its report path. A rule after the write can record the problem, but only an earlier lifecycle boundary can stop the effect.',
        prompt: 'Is a post-tool hook too late to protect the filesystem?',
        takeaway: 'A control must run at an event with enough evidence and enough remaining authority to intervene.',
        presenterCue: 'Move along a before–during–after timeline and ask at which point prevention becomes impossible.',
      },
      {
        id: 'hooks-lifecycle/mechanism',
        kind: 'mechanism',
        eyebrow: 'Attach rules to events',
        title: 'Hooks make selected lifecycle behavior repeatable and observable.',
        summary: 'The harness emits structured events around prompts, tool proposals, execution, compaction, delegation, and stopping. Handlers can inspect the event and return an allow, deny, transform, validation, recovery, or audit result.',
        steps: [
          { label: 'Observe', expression: 'Receive the event payload', copy: 'The event supplies the proposal, result, state, or transition available at that point.' },
          { label: 'Evaluate', expression: 'Apply deterministic logic', copy: 'The handler checks paths, provenance, formatting, budgets, or terminal requirements.' },
          { label: 'Return', expression: 'Control the transition', copy: 'The harness applies an allow, deny, transform, retry, or explicit failure.' },
          { label: 'Audit', expression: 'Record the intervention', copy: 'The trace links the hook decision to its input and the resulting system behavior.' },
        ],
        takeaway: 'Hooks are lifecycle automation; authorization and sandboxing remain separate layers.',
        presenterCue: 'Keep prevention, validation, recovery, and observation distinct while placing examples on the timeline.',
      },
      {
        id: 'hooks-lifecycle/practice',
        kind: 'practice',
        eyebrow: 'Place the intervention',
        title: 'Choose the earliest useful hook for four laptop-run rules.',
        summary: 'Place a protected-path check, an evidence-provenance validator, a post-compaction state restore, and a pre-stop report verifier at lifecycle events where each can succeed.',
        steps: [
          { label: 'Prevent', expression: 'Block an unsafe write', copy: 'Use the last pre-execution boundary that sees normalized arguments and can still deny the call.' },
          { label: 'Validate', expression: 'Inspect returned evidence', copy: 'Check source and timestamp metadata after the read tool has produced an observation.' },
          { label: 'Recover', expression: 'Restore required state', copy: 'After compaction, rebuild the terminal checklist from an authoritative external record.' },
          { label: 'Gate', expression: 'Verify before stopping', copy: 'Require a readable report and current evidence before accepting completion.' },
        ],
        prompt: 'For each rule, what is the earliest event with all required evidence and control?',
        takeaway: 'Hook placement follows evidence availability and intervention timing.',
        presenterCue: 'Let the group choose one deliberately late event, then expose what that placement can no longer prevent.',
      },
      {
        id: 'hooks-lifecycle/debrief',
        kind: 'debrief',
        eyebrow: 'Respect the boundary',
        title: 'A hook covers named transitions, not the entire system.',
        summary: 'The protected write is stopped before execution, while provenance is checked after a read. Neither hook grants identity, replaces tool authorization, or isolates the underlying process.',
        prompt: 'Which failure would still escape these hooks and require policy, permissions, or a sandbox?',
        takeaway: 'Hooks strengthen known lifecycle points but are not a universal security boundary.',
        presenterCue: 'Bridge from attachment points to the complete acceptance boundary for every tool proposal.',
      },
    ),
  },
  'tool-boundaries': {
    lessonId: 'tool-boundaries',
    moments: fourMoments(
      {
        id: 'tool-boundaries/hook',
        kind: 'hook',
        eyebrow: 'Begin with authority',
        title: 'If the model can name an action, can it perform it?',
        summary: 'A retrieved page tells the laptop researcher to buy now, and the model proposes a purchase call. The proposal is structured data—not identity, permission, approval, or proof of execution.',
        prompt: 'Can a stronger system prompt create a reliable purchase boundary?',
        takeaway: 'Prompts influence proposals; deterministic controls govern capability.',
        presenterCue: 'Ask whether syntactically valid arguments make an action authorized before revealing the layered checks.',
      },
      {
        id: 'tool-boundaries/mechanism',
        kind: 'mechanism',
        eyebrow: 'Mediate every effect',
        title: 'A proposal must pass through code before it reaches the environment.',
        summary: 'The harness resolves an explicitly exposed capability, parses its arguments, validates meaning, checks the current principal and task policy, obtains exact approval when required, executes within limits, and normalizes the outcome.',
        steps: [
          { label: 'Resolve', expression: 'Find an exposed capability', copy: 'Unknown or unavailable tools fail before any implementation is reached.' },
          { label: 'Validate', expression: 'Check structure and meaning', copy: 'Malformed, ambiguous, or out-of-range arguments fail closed.' },
          { label: 'Authorize', expression: 'Check principal and scope', copy: 'Least privilege, task policy, and any exact approval determine whether execution is allowed.' },
          { label: 'Execute', expression: 'Constrain and observe', copy: 'A bounded executor performs the action and reports what actually happened.' },
        ],
        takeaway: 'Capability is explicit, least-privileged, observable, and interruptible.',
        presenterCue: 'Visually separate proposal validation from authorization; a valid shape does not imply permission.',
      },
      {
        id: 'tool-boundaries/practice',
        kind: 'practice',
        eyebrow: 'Gate the proposals',
        title: 'Decide the fate of four laptop-agent tool calls.',
        summary: 'Evaluate a catalog read, an authorized report write, a path-traversal write, and a purchase proposal. Identify the first boundary that should reject or constrain each call.',
        steps: [
          { label: 'Inspect', expression: 'Read name and arguments', copy: 'Treat every field as untrusted model output, even when it looks plausible.' },
          { label: 'Decide', expression: 'Allow, approve, or deny', copy: 'Apply schema, semantics, identity, task scope, and risk in the correct order.' },
          { label: 'Compare', expression: 'Check the real outcome', copy: 'Distinguish the proposed action, executor response, and verified environment state.' },
        ],
        prompt: 'What evidence proves that laptop-comparison.md was written safely and that no purchase occurred?',
        takeaway: 'A trustworthy trace connects each proposal to its boundary decision and actual outcome.',
        presenterCue: 'Keep all effects simulated and ask learners to name the earliest decisive rejection for each call.',
      },
      {
        id: 'tool-boundaries/debrief',
        kind: 'debrief',
        eyebrow: 'Measure the blast radius',
        title: 'The purchase proposal failed safely because authority never existed.',
        summary: 'The research agent cannot turn retrieved instructions into purchasing power. The capability is absent or denied, the report write remains path-scoped, and the environment outcome—not the model’s narration—establishes success.',
        prompt: 'Which single reduction in exposed capability most directly limits the task’s blast radius?',
        takeaway: 'Least functionality and least privilege make model mistakes survivable.',
        presenterCue: 'Bridge to evaluation: a safe-looking architecture is still a hypothesis until repeated traces test it.',
      },
    ),
  },
  'agent-evals': {
    lessonId: 'agent-evals',
    moments: fourMoments(
      {
        id: 'agent-evals/hook',
        kind: 'hook',
        eyebrow: 'Begin with uncertainty',
        title: 'Does one excellent laptop report prove the agent is reliable?',
        summary: 'A polished demonstration can hide intermittent missing citations, stale prices, excessive retries, unsafe proposals, or lucky tool results. Reliability is a distribution of runs, not a favorite transcript.',
        prompt: 'Would you deploy an agent that succeeds once in three attempts if that one result looks perfect?',
        takeaway: 'Agent evaluation must capture variability across tasks, trajectories, effects, cost, and risk.',
        presenterCue: 'Ask for a decision after hearing only “one beautiful demo,” then reveal the failed runs.',
      },
      {
        id: 'agent-evals/mechanism',
        kind: 'mechanism',
        eyebrow: 'Build credible evidence',
        title: 'Freeze the contract, repeat trials, grade outcomes, then inspect traces.',
        summary: 'A versioned evaluation fixes the task, environment, model, harness, policies, and budgets for comparison. Repeated runs expose variance; suitable graders check observable outcomes and forbidden effects; trace review explains the scores.',
        steps: [
          { label: 'Specify', expression: 'Define success and non-goals', copy: 'Make the report requirements, evidence freshness, path, and forbidden purchase effects measurable.' },
          { label: 'Repeat', expression: 'Run independent trials', copy: 'Sample stochastic behavior and environment variation instead of trusting one attempt.' },
          { label: 'Grade', expression: 'Match checks to evidence', copy: 'Use deterministic checks for files and effects, and calibrated rubrics only where judgment is necessary.' },
          { label: 'Diagnose', expression: 'Inspect failed trajectories', copy: 'Separate task, model, harness, tool, environment, and grader failures before changing the system.' },
        ],
        takeaway: 'A score summarizes evidence; it does not replace outcome and trace inspection.',
        presenterCue: 'Keep task, trial, trace, outcome, and grader as visibly separate objects.',
      },
      {
        id: 'agent-evals/practice',
        kind: 'practice',
        eyebrow: 'Evaluate the whole run',
        title: 'Design a test suite for the laptop researcher.',
        summary: 'Run repeated fixtures with timeouts, conflicting prices, missing evidence, path attacks, and injected purchase instructions. Grade both the report and the full sequence of effects.',
        steps: [
          { label: 'Define', expression: 'Write observable checks', copy: 'Check three candidates, current citations, budget compliance, report read-back, and zero forbidden effects.' },
          { label: 'Repeat', expression: 'Compare multiple attempts', copy: 'Track success, consistency, retries, cost, latency, and unsafe proposals across runs.' },
          { label: 'Inspect', expression: 'Open a failed trace', copy: 'Identify the first causal failure instead of optimizing a dashboard number blindly.' },
        ],
        prompt: 'Did the candidate change improve capability, consistency, efficiency, or only the best-looking response?',
        takeaway: 'Evaluation is useful when failures point to an actionable system boundary.',
        presenterCue: 'Have learners optimize one metric, then name what that change might make worse.',
      },
      {
        id: 'agent-evals/debrief',
        kind: 'debrief',
        eyebrow: 'Read behind the score',
        title: 'The failed trace explains what the aggregate concealed.',
        summary: 'Repeated trials reveal whether the model proposed poorly, the harness admitted the wrong action, a tool returned bad evidence, the environment changed, or the grader rewarded the wrong outcome.',
        prompt: 'Which failure category would require changing the harness rather than the prompt?',
        takeaway: 'Reliable improvement comes from versioned comparisons and causal failure analysis.',
        presenterCue: 'Bridge to the capstone by asking learners to defend an architecture with this evidence, not intuition.',
      },
    ),
  },
  capstone: {
    lessonId: 'capstone',
    moments: fourMoments(
      {
        id: 'capstone/hook',
        kind: 'hook',
        eyebrow: 'Begin with the complete claim',
        title: 'Can the laptop agent be useful without receiving purchase authority?',
        summary: 'The final design must research three laptops under €900, preserve current evidence, write and verify laptop-comparison.md, recover from bounded failures, and make purchase or vendor contact impossible.',
        prompt: 'What would you need to inspect before trusting this system with the research task?',
        takeaway: 'A complete agent design connects utility, authority, recoverability, and evaluation.',
        presenterCue: 'Treat the scenario as an architecture review: ask for evidence, not feature names.',
      },
      {
        id: 'capstone/mechanism',
        kind: 'mechanism',
        eyebrow: 'Integrate the ownership map',
        title: 'Every proposal, decision, effect, record, and verdict needs an owner.',
        summary: 'The user owns the goal and approvals; the model proposes research and synthesis; the harness owns context, orchestration, policy, state, budgets, and stopping; tools affect the environment; external records preserve evidence; evaluators judge the run.',
        steps: [
          { label: 'Contract', expression: 'Define success and non-goals', copy: 'Turn the request into measurable evidence, artifact, safety, and terminal conditions.' },
          { label: 'Own', expression: 'Assign every responsibility', copy: 'Keep model judgment distinct from deterministic harness controls and environment truth.' },
          { label: 'Trace', expression: 'Follow one representative run', copy: 'Connect context selection, proposals, boundary decisions, observations, artifacts, and stops.' },
          { label: 'Test', expression: 'Attack and repeat', copy: 'Exercise stale evidence, failures, unsafe instructions, recovery, and evaluation variance.' },
        ],
        takeaway: 'The model is one component inside a governed, observable system.',
        presenterCue: 'Build the architecture outward from the harness and ask who owns each arrow.',
      },
      {
        id: 'capstone/practice',
        kind: 'practice',
        eyebrow: 'Defend the architecture',
        title: 'Design, trace, and threat-model the complete research agent.',
        summary: 'Specify the task contract, context policy, durable state, delegation plan, hook placement, tool boundary, recovery strategy, and repeated evaluation suite for the shared laptop scenario.',
        steps: [
          { label: 'Design', expression: 'Draw the system and contracts', copy: 'Include owners, trusted boundaries, exact artifacts, evidence stores, and explicit non-goals.' },
          { label: 'Walk', expression: 'Trace success and recovery', copy: 'Show one verified report run and one stale-evidence or tool-failure recovery path.' },
          { label: 'Attack', expression: 'Propose a forbidden purchase', copy: 'Prove where the proposal is denied and how zero external effect is verified.' },
          { label: 'Evaluate', expression: 'Define release evidence', copy: 'State repeated outcome, safety, cost, latency, and failure-analysis criteria.' },
        ],
        prompt: 'Which claim in your design still depends on trusting model prose rather than inspectable state?',
        takeaway: 'A defensible architecture turns every important claim into a boundary, trace event, or measurable outcome.',
        presenterCue: 'Challenge vague verbs such as “remembers,” “uses,” and “completes” until the mechanism and owner are explicit.',
      },
      {
        id: 'capstone/debrief',
        kind: 'debrief',
        eyebrow: 'Close the narrative',
        title: 'The system is useful because its freedom is bounded and inspectable.',
        summary: 'The laptop agent can adapt its research while the harness preserves authority, exact evidence, safe tool use, recoverability, and a measurable terminal state. Variability remains inside boundaries that can be tested.',
        prompt: 'If the task changed from research-only to an approved purchase, which contracts and controls would need to change?',
        takeaway: 'Agent quality is the joint quality of model proposals, harness decisions, tool effects, environment evidence, and evaluation.',
        presenterCue: 'End by revisiting the opening question and have learners name what belongs to the model, harness, and environment.',
      },
    ),
  },
};
