import type { LessonTeachingMoments, TeachingMoment } from '../../teachingMoments/types';
import type { LlmCourseLessonId } from '../llmCourseCatalog';

const teachingMoment = (moment: TeachingMoment) => moment;

export const LLM_LESSON_MOMENTS = {
  'prediction-goal': {
    lessonId: 'prediction-goal',
    moments: [
      teachingMoment({
        id: 'prediction-goal/hook',
        kind: 'hook',
        eyebrow: 'One unfinished sentence',
        title: 'What should come after “too”?',
        summary: '“Tired,” “dark,” and “late” can all be plausible. The model must represent alternatives before a decoder selects one.',
        prompt: 'Write down three continuations and decide whether more than one can be reasonable.',
        takeaway: 'The immediate task has several plausible answers, not one hidden completion.',
        presenterCue: 'Collect several answers before revealing any model distribution.',
      }),
      teachingMoment({
        id: 'prediction-goal/mechanism',
        kind: 'mechanism',
        eyebrow: 'Prediction contract',
        title: 'One forward pass scores one next-token position',
        summary: 'Given the tokens already visible, the model produces one score for every vocabulary item. Softmax turns those scores into a conditional distribution.',
        steps: [
          { label: 'Input', expression: 'x_{1:t}', copy: 'The token sequence seen so far.' },
          { label: 'Model', expression: 'z = f_\\theta(x_{1:t})', copy: 'A forward pass returns vocabulary logits.' },
          { label: 'Distribution', expression: 'p_i = \\operatorname{softmax}(z)_i', copy: 'Each token receives a conditional probability.' },
        ],
        takeaway: 'A forward pass returns a next-token distribution, not a completed sentence.',
        presenterCue: 'Point to the representation change: context sequence → vocabulary-width score vector.',
      }),
      teachingMoment({
        id: 'prediction-goal/practice',
        kind: 'practice',
        eyebrow: 'Predict, then inspect',
        title: 'Separate model scores from decoder choice',
        summary: 'Compare the same distribution under greedy selection and seeded sampling. Then edit one earlier word and run the prediction again.',
        prompt: 'Which changes came from the prompt, and which came only from the selection rule?',
        takeaway: 'Context affects the distribution; decoding decides how one candidate is selected from it.',
        presenterCue: 'Ask for predictions before each run and keep probability changes separate from selected-token changes.',
      }),
      teachingMoment({
        id: 'prediction-goal/debrief',
        kind: 'debrief',
        eyebrow: 'What the model knows now',
        title: 'Plausibility is not a truth test',
        summary: 'The probabilities describe likely continuations under the model and current context. They do not certify that a statement is true or that the whole answer is correct.',
        takeaway: 'Generation is repeated conditional prediction: choose, append, and predict again.',
        presenterCue: 'Close by asking what representation the model needs before it can make this prediction: token IDs.',
      }),
    ],
  },
  tokenization: {
    lessonId: 'tokenization',
    moments: [
      teachingMoment({
        id: 'tokenization/hook',
        kind: 'hook',
        eyebrow: 'The model’s alphabet',
        title: 'The sentence on screen is not the sequence the model receives',
        summary: 'Spaces, capitalization, names, code, emoji, and language can all change token boundaries and sequence length.',
        prompt: 'Predict which is likely to use more tokens: a familiar word, a rare surname, or one emoji.',
        takeaway: 'Visible words and model tokens are different units.',
        presenterCue: 'Let learners mark human word boundaries before showing tokenizer boundaries.',
      }),
      teachingMoment({
        id: 'tokenization/mechanism',
        kind: 'mechanism',
        eyebrow: 'Discrete representation',
        title: 'A stored codebook maps exact text to ordered IDs',
        summary: 'A tokenizer applies learned vocabulary and segmentation rules. Each resulting ID is a categorical address, not a coordinate or semantic measurement.',
        steps: [
          { label: 'Text', expression: 'Unicode text', copy: 'The application supplies exact characters and formatting.' },
          { label: 'Pieces', expression: '[s_1, s_2, …, s_n]', copy: 'Tokenizer-specific reusable fragments.' },
          { label: 'IDs', expression: '[i_1, i_2, …, i_n]', copy: 'Ordered vocabulary-row addresses.' },
        ],
        takeaway: 'Tokenization defines the discrete sequence the neural network will process.',
        presenterCue: 'Emphasize that the integer distance between two IDs has no semantic meaning.',
      }),
      teachingMoment({
        id: 'tokenization/practice',
        kind: 'practice',
        eyebrow: 'Boundary experiment',
        title: 'Change one surface detail at a time',
        summary: 'Compare “tired,” “Tired,” “ very tired,” a rare name, and an emoji. Inspect pieces, IDs, and total sequence length.',
        prompt: 'Which edit changes only IDs, and which edit also changes the number of positions?',
        takeaway: 'Token boundaries are tokenizer-specific and operationally important.',
        presenterCue: 'Have the learner predict the longest sequence before revealing the encoding.',
      }),
      teachingMoment({
        id: 'tokenization/debrief',
        kind: 'debrief',
        eyebrow: 'Representation boundary',
        title: 'IDs identify rows; they do not yet carry neural geometry',
        summary: 'The tokenizer has produced an inspectable sequence of categorical addresses. Context length, compute, and later attention all depend on this sequence.',
        takeaway: 'The next operation must look up a learned vector for every ID and introduce position.',
        presenterCue: 'Bridge with the question: what useful numerical operation can a network perform on address 42 itself?',
      }),
    ],
  },
  'token-embeddings': {
    lessonId: 'token-embeddings',
    moments: [
      teachingMoment({
        id: 'token-embeddings/hook',
        kind: 'hook',
        eyebrow: 'From symbols to geometry',
        title: 'An ID is an address, so what does the network actually calculate with?',
        summary: 'The model replaces each categorical ID with a learned row of real numbers and makes token order available through position information.',
        prompt: 'Would averaging token IDs create a meaningful representation? Explain why or why not.',
        takeaway: 'Neural computation begins after lookup, not on the ID numbers themselves.',
        presenterCue: 'Contrast a database row number with the numerical contents stored in that row.',
      }),
      teachingMoment({
        id: 'token-embeddings/mechanism',
        kind: 'mechanism',
        eyebrow: 'Initial token state',
        title: 'Lookup supplies identity; position supplies order',
        summary: 'For each position, the token ID selects an embedding row. A positional signal is added or otherwise incorporated to form the first model-width state.',
        steps: [
          { label: 'Lookup', expression: 'e_t = E[i_t]', copy: 'Select one learned row from the embedding table.' },
          { label: 'Position', expression: 'r_t^{(0)} = e_t + p_t', copy: 'Combine token identity with its location in the sequence.' },
          { label: 'Sequence state', expression: 'R_0 \\in \\mathbb{R}^{n \\times d_{model}}', copy: 'One fixed-width vector for each token position.' },
        ],
        takeaway: 'The output is an initial token-state matrix, not a sentence embedding and not yet a contextual meaning.',
        presenterCue: 'Keep token lookup vectors, contextual states, and retrieval embeddings visibly separated.',
      }),
      teachingMoment({
        id: 'token-embeddings/practice',
        kind: 'practice',
        eyebrow: 'Inspect the starting state',
        title: 'Hold the token constant and move its position',
        summary: 'Compare the same token at two positions, then compare two token IDs at one position. Identify which part of the initial state changed.',
        prompt: 'Which differences come from token identity, which from position, and which require later context processing?',
        takeaway: 'Initial states expose identity and order; contextual distinctions emerge inside transformer blocks.',
        presenterCue: 'Use the public embedding observatory as geometry evidence, never as a claim about Bonsai’s private weights.',
      }),
      teachingMoment({
        id: 'token-embeddings/debrief',
        kind: 'debrief',
        eyebrow: 'Starting point, not definition',
        title: 'The same token can begin alike and end differently',
        summary: 'A reusable lookup row is transformed according to surrounding tokens. Later states can therefore differ even when the original token ID is identical.',
        takeaway: 'Token embeddings initialize computation; transformer blocks create context-dependent token states.',
        presenterCue: 'Bridge by asking which two jobs repeatedly update this matrix without changing its shape.',
      }),
    ],
  },
  'transformer-block': {
    lessonId: 'transformer-block',
    moments: [
      teachingMoment({
        id: 'transformer-block/hook',
        kind: 'hook',
        eyebrow: 'Two jobs per block',
        title: 'How can “too” gather a clue and then compute with it?',
        summary: 'A decoder block alternates communication across token positions with local transformation at each position.',
        prompt: 'Which operation must cross positions: attention, the MLP, or residual addition?',
        takeaway: 'Attention communicates; the MLP computes locally.',
        presenterCue: 'Ask learners to assign one verb—communicate or compute—to each branch before showing the block.',
      }),
      teachingMoment({
        id: 'transformer-block/mechanism',
        kind: 'mechanism',
        eyebrow: 'Pre-norm decoder block',
        title: 'Each branch writes an update into the residual state',
        summary: 'Normalization prepares each branch, attention gathers allowed context, the MLP transforms each row, and residual additions preserve the shared state.',
        steps: [
          { label: 'Communicate', expression: 'R\' = R + \\operatorname{Attn}(\\operatorname{Norm}(R))', copy: 'Attention mixes information between allowed positions.' },
          { label: 'Compute', expression: 'R_{next} = R\' + \\operatorname{MLP}(\\operatorname{Norm}(R\'))', copy: 'The MLP transforms every position independently.' },
          { label: 'Contract', expression: 'n \\times d_{model} \\rightarrow n \\times d_{model}', copy: 'The state shape stays constant across the block.' },
        ],
        takeaway: 'A block refines the existing token states through additive updates.',
        presenterCue: 'Trace the row for “too” through both branches and keep the order explicit.',
      }),
      teachingMoment({
        id: 'transformer-block/practice',
        kind: 'practice',
        eyebrow: 'Intervention',
        title: 'Remove one branch and name the missing capability',
        summary: 'Disable attention, then restore it and disable the MLP. Observe how the educational miniature’s token states respond.',
        prompt: 'Did the intervention remove cross-position routing or position-wise transformation?',
        takeaway: 'The branches are complementary and neither branch alone is the complete transformer.',
        presenterCue: 'Require a prediction before toggling each branch; distinguish structural insight from exact model behavior.',
      }),
      teachingMoment({
        id: 'transformer-block/debrief',
        kind: 'debrief',
        eyebrow: 'Stacked refinement',
        title: 'Depth composes many partial updates',
        summary: 'One block rarely owns a tidy linguistic rule. Repeated attention and MLP updates build increasingly contextual numerical states across the stack.',
        takeaway: 'The transformer is a sequence of stable representation contracts, not one mysterious operation.',
        presenterCue: 'Zoom into the communication branch next: queries, keys, values, masking, and weighted mixing.',
      }),
    ],
  },
  attention: {
    lessonId: 'attention',
    moments: [
      teachingMoment({
        id: 'attention/hook',
        kind: 'hook',
        eyebrow: 'Route the clue',
        title: 'Which earlier positions should “too” consult?',
        summary: 'The final prompt position needs useful information from the allowed prefix before it can support a continuation such as “tired.”',
        prompt: 'Choose one earlier token to inspect and state what useful information it might carry.',
        takeaway: 'Attention moves selected information to the position that needs it.',
        presenterCue: 'Collect hypotheses without treating any chosen word as the model’s measured explanation.',
      }),
      teachingMoment({
        id: 'attention/mechanism',
        kind: 'mechanism',
        eyebrow: 'Query, key, value',
        title: 'Match questions to addresses, then mix content',
        summary: 'Learned projections create runtime queries, keys, and values. Scaled dot products, a causal mask, and softmax produce weights used to mix value vectors.',
        steps: [
          { label: 'Project', expression: 'Q=XW_Q,\\;K=XW_K,\\;V=XW_V', copy: 'Create head-specific runtime activations.' },
          { label: 'Weight', expression: 'A=\\operatorname{softmax}(QK^\\top/\\sqrt{d_k}+M)', copy: 'Mask future positions and normalize allowed scores.' },
          { label: 'Gather', expression: 'O=AV', copy: 'Form a weighted mixture of value vectors.' },
        ],
        takeaway: 'Attention weights control value mixing; a weight alone is not the information being moved.',
        presenterCue: 'Keep destination rows and source columns explicit, and show why each causal row sums to one.',
      }),
      teachingMoment({
        id: 'attention/practice',
        kind: 'practice',
        eyebrow: 'Glass-box calculation',
        title: 'Calculate one attention row for “too”',
        summary: 'Inspect scores, apply the causal mask, normalize the allowed sources, and combine their displayed values.',
        prompt: 'If the largest weight changes, must the final next-token choice change? What else lies downstream?',
        takeaway: 'A heatmap is one measured routing pattern inside a larger causal pipeline.',
        presenterCue: 'Ask learners to distinguish an exact miniature calculation from an unobserved production-model claim.',
      }),
      teachingMoment({
        id: 'attention/debrief',
        kind: 'debrief',
        eyebrow: 'Interpret carefully',
        title: 'Attention is routing, not a transcript of reasoning',
        summary: 'Multiple heads, value contents, output projections, residual additions, later blocks, and the language-model head all affect the final distribution.',
        takeaway: 'An attention pattern is diagnostic evidence, not a complete causal explanation.',
        presenterCue: 'Bridge by asking where the attention update goes after it is calculated: into the residual stream.',
      }),
    ],
  },
  'residual-stream': {
    lessonId: 'residual-stream',
    moments: [
      teachingMoment({
        id: 'residual-stream/hook',
        kind: 'hook',
        eyebrow: 'Shared working state',
        title: 'Where does the clue gathered by attention go?',
        summary: 'Every token position carries a fixed-width numerical state through the stack while attention and MLP branches add updates.',
        prompt: 'Should a useful earlier feature be replaced, stored separately, or combined with the new update?',
        takeaway: 'Residual addition lets old state and new evidence coexist.',
        presenterCue: 'Use the metaphor of annotations on one working page, then immediately restate that the page is numerical state.',
      }),
      teachingMoment({
        id: 'residual-stream/mechanism',
        kind: 'mechanism',
        eyebrow: 'Additive state',
        title: 'Components read from and write to the same-shaped stream',
        summary: 'Each branch computes an update from the current token-state matrix and adds it back. The tensor shape persists while its contents become more contextual.',
        steps: [
          { label: 'Current state', expression: 'R_\\ell \\in \\mathbb{R}^{n\\times d_{model}}', copy: 'One row per current token position.' },
          { label: 'Update', expression: '\\Delta R_\\ell = g_\\ell(R_\\ell)', copy: 'An attention or MLP branch proposes a change.' },
          { label: 'Accumulate', expression: 'R_{\\ell+1}=R_\\ell+\\Delta R_\\ell', copy: 'The updated state enters later computation.' },
        ],
        takeaway: 'The stream preserves a stable interface while depth accumulates distributed features.',
        presenterCue: 'Keep activation state distinct from model parameters and from cached K/V tensors.',
      }),
      teachingMoment({
        id: 'residual-stream/practice',
        kind: 'practice',
        eyebrow: 'Probe through depth',
        title: 'Track candidates without inventing hidden prose',
        summary: 'Scrub through displayed layers and project intermediate states through the specified vocabulary lens. Watch candidate scores rise and fall.',
        prompt: 'What did the probe measure, and what would be an unjustified claim about a private thought?',
        takeaway: 'A lens interprets an intermediate state; it does not reveal a sentence stored inside it.',
        presenterCue: 'Ask learners to say “the probe scores…” instead of “the model is thinking…”.',
      }),
      teachingMoment({
        id: 'residual-stream/debrief',
        kind: 'debrief',
        eyebrow: 'Final contextual state',
        title: 'The last position now carries the context needed for prediction',
        summary: 'After the final block, the row for the last prompt position is still a model-width vector. It has not yet become vocabulary probabilities.',
        takeaway: 'The language-model head must change the representation from model width to vocabulary width.',
        presenterCue: 'Place the two shapes side by side: d_model values now, V token scores next.',
      }),
    ],
  },
  'language-model-head': {
    lessonId: 'language-model-head',
    moments: [
      teachingMoment({
        id: 'language-model-head/hook',
        kind: 'hook',
        eyebrow: 'From state to alternatives',
        title: 'How can one vector compete against an entire vocabulary?',
        summary: 'The final state for “too” contains contextual numerical features, but a decoder needs one score for every possible next token.',
        prompt: 'Which representation is wider: the final token state or the vocabulary score row?',
        takeaway: 'Prediction requires a projection from model space into vocabulary space.',
        presenterCue: 'Ask learners to name the current and required output shapes before showing the head.',
      }),
      teachingMoment({
        id: 'language-model-head/mechanism',
        kind: 'mechanism',
        eyebrow: 'Unembed, normalize, choose',
        title: 'The model scores; the decoder selects',
        summary: 'A final normalization and output projection create logits. Temperature and softmax create a distribution; an application-level decoding rule selects one token.',
        steps: [
          { label: 'Logits', expression: 'z=W_U\\operatorname{Norm}(h_t)+b', copy: 'Map one model-width state to V raw token scores.' },
          { label: 'Probability', expression: 'p_i=\\operatorname{softmax}(z/T)_i', copy: 'Normalize temperature-scaled scores.' },
          { label: 'Decode', expression: 'y \\sim p \\;\\text{or}\\; y=\\arg\\max_i p_i', copy: 'Sample or choose the highest-probability token.' },
        ],
        takeaway: 'Model computation and decoding policy are separate stages.',
        presenterCue: 'Mark the boundary between learned model outputs and application-controlled selection.',
      }),
      teachingMoment({
        id: 'language-model-head/practice',
        kind: 'practice',
        eyebrow: 'Distribution experiment',
        title: 'Change temperature without changing logits',
        summary: 'Compare greedy decoding and seeded sampling while inspecting the same candidate logits at several positive temperatures.',
        prompt: 'What changed: token ranking, distribution concentration, selected output, or learned knowledge?',
        takeaway: 'Positive temperature changes concentration without changing the ordering of fixed logits.',
        presenterCue: 'Separate deterministic distribution changes from stochastic selection outcomes.',
      }),
      teachingMoment({
        id: 'language-model-head/debrief',
        kind: 'debrief',
        eyebrow: 'One token emitted',
        title: 'The choice becomes new context, not a finished answer',
        summary: 'The selected token is appended to the sequence. The model must run another next-token step to continue the response.',
        takeaway: 'A probability is conditional on exact context and model state; it is not global confidence or factual certainty.',
        presenterCue: 'Bridge by asking which earlier calculations can be reused after one token is appended.',
      }),
    ],
  },
  'generation-cache': {
    lessonId: 'generation-cache',
    moments: [
      teachingMoment({
        id: 'generation-cache/hook',
        kind: 'hook',
        eyebrow: 'Append and repeat',
        title: 'Must every generated token recompute the entire prefix?',
        summary: 'Earlier token positions produced keys and values that later queries still need. With fixed weights and prefix, those projections can be reused.',
        prompt: 'Which runtime tensors stay useful after the model appends one new token?',
        takeaway: 'Autoregressive generation repeats prediction but can reuse prefix computation.',
        presenterCue: 'Contrast the long prefill pass with the single-new-position decode pass.',
      }),
      teachingMoment({
        id: 'generation-cache/mechanism',
        kind: 'mechanism',
        eyebrow: 'Request-scoped working shelf',
        title: 'The KV cache retains attention inputs from earlier positions',
        summary: 'Prefill creates keys and values for every prompt position at every layer. Each decode step reads those rows and appends the new position’s rows.',
        steps: [
          { label: 'Prefill', expression: 'K_{1:n},V_{1:n}', copy: 'Process the prompt and populate the cache.' },
          { label: 'Decode', expression: 'q_{n+1}K_{1:n+1}^{\\top}', copy: 'The new query reads old and new key rows.' },
          { label: 'Append', expression: 'cache \\leftarrow cache \\cup (k_{n+1},v_{n+1})', copy: 'Retain the newest rows for the next step.' },
        ],
        takeaway: 'The cache stores temporary K/V activations, not learned facts or token probabilities.',
        presenterCue: 'Show the cache growing by one logical row per new position and per layer.',
      }),
      teachingMoment({
        id: 'generation-cache/practice',
        kind: 'practice',
        eyebrow: 'Systems tradeoff',
        title: 'Trade repeated compute for active-sequence memory',
        summary: 'Compare short and long prompts, then vary layer count, KV-head count, context length, and element width in the cache estimator.',
        prompt: 'Which dimension increases time to first token, and which dimensions increase cache memory linearly?',
        takeaway: 'Caching accelerates decode while memory grows with the retained K/V tensor shapes.',
        presenterCue: 'Derive from displayed tensor dimensions instead of asking learners to memorize one universal byte formula.',
      }),
      teachingMoment({
        id: 'generation-cache/debrief',
        kind: 'debrief',
        eyebrow: 'Temporary state',
        title: 'Fast reuse is not long-term memory',
        summary: 'Clearing a KV cache discards request computation but does not erase learned weights. Keeping it does not train the model or permanently store a conversation.',
        takeaway: 'Weights hold learned parameters; the KV cache holds prompt-dependent inference activations.',
        presenterCue: 'Bridge from fixed inference weights to the final question: how were those parameters learned?',
      }),
    ],
  },
  learning: {
    lessonId: 'learning',
    moments: [
      teachingMoment({
        id: 'learning/hook',
        kind: 'hook',
        eyebrow: 'When the target was “tired”',
        title: 'What happens if the model assigned the observed token low probability?',
        summary: 'Training turns a poor next-token prediction into a scalar error signal, then uses it to make a small distributed parameter update.',
        prompt: 'Should showing one answer once make the model remember it perfectly? Why would that be risky?',
        takeaway: 'Learning is repeated numerical adjustment, not writing an answer into one memory slot.',
        presenterCue: 'Start from the exact distribution produced in the inference story, then introduce the observed target.',
      }),
      teachingMoment({
        id: 'learning/mechanism',
        kind: 'mechanism',
        eyebrow: 'Loss, gradients, optimizer',
        title: 'Measure the miss, assign responsibility, update parameters',
        summary: 'Cross-entropy measures how little probability reached the observed token. Backpropagation computes gradients; the optimizer uses them to change weights.',
        steps: [
          { label: 'Loss', expression: 'L=-\\log p_\\theta(y_t\\mid x_{<t})', copy: 'Low target probability produces a larger penalty.' },
          { label: 'Backward', expression: 'g=\\nabla_\\theta L', copy: 'Compute how parameters contributed to the loss.' },
          { label: 'Update', expression: '\\theta \\leftarrow \\theta-\\eta g', copy: 'An optimizer applies a small illustrative gradient step.' },
        ],
        takeaway: 'Loss, backpropagation, and optimization perform different jobs.',
        presenterCue: 'Do not say that backpropagation itself updates weights; point to the optimizer as the update policy.',
      }),
      teachingMoment({
        id: 'learning/practice',
        kind: 'practice',
        eyebrow: 'Follow one training step',
        title: 'Move target probability and watch the penalty change',
        summary: 'Set the observed token probability to 0.1, 0.5, and 0.9. Compare loss, inspect gradient direction, and apply one miniature optimizer step.',
        prompt: 'Where does ordinary inference end, and at what exact operation do learned parameters begin to change?',
        takeaway: 'Inference creates activations; training additionally computes gradients and changes parameters.',
        presenterCue: 'Label all numbers as educational miniature values, not measurements from the production model.',
      }),
      teachingMoment({
        id: 'learning/debrief',
        kind: 'debrief',
        eyebrow: 'Distributed learning',
        title: 'One update nudges behavior; evaluation tests what generalized',
        summary: 'A training step changes many parameters slightly. Its effects can transfer, interfere, or overfit, so unseen examples must test whether learning was useful.',
        takeaway: 'Prompting changes runtime context; training changes weights through repeated evaluated updates.',
        presenterCue: 'Bridge to the capstone: identify which objects change during inference and which only change during training.',
      }),
    ],
  },
  capstone: {
    lessonId: 'capstone',
    moments: [
      teachingMoment({
        id: 'capstone/hook',
        kind: 'hook',
        eyebrow: 'Change one word',
        title: 'If “animal” becomes “robot,” what changes—and what stays fixed?',
        summary: 'The edit begins a chain of representation dependencies, but some exact downstream results cannot be known without executing the tokenizer or model.',
        prompt: 'Classify your predictions as directly inspectable, model-dependent, application-controlled, or fixed.',
        takeaway: 'A good explanation distinguishes known dependencies from unmeasured values.',
        presenterCue: 'Collect claims first, then require an evidence class for each one.',
      }),
      teachingMoment({
        id: 'capstone/mechanism',
        kind: 'mechanism',
        eyebrow: 'Complete representation ledger',
        title: 'Trace every boundary from text to one selected token',
        summary: 'At each stage, name the input representation, operation, output shape, controlling component, and evidence supporting the claim.',
        steps: [
          { label: 'Discrete', expression: 'text \\rightarrow token\\ IDs', copy: 'Tokenizer-dependent and directly inspectable by running it.' },
          { label: 'Continuous', expression: 'states \\rightarrow contextual\\ states', copy: 'Model-dependent activations produced by the transformer.' },
          { label: 'Decision', expression: 'logits \\rightarrow probabilities \\rightarrow token', copy: 'Model scoring followed by application decoding.' },
        ],
        takeaway: 'The complete system is a chain of explicit representation contracts.',
        presenterCue: 'Keep exact miniature arithmetic, live runtime observations, and schematic explanations visually distinct.',
      }),
      teachingMoment({
        id: 'capstone/practice',
        kind: 'practice',
        eyebrow: 'Two-prompt audit',
        title: 'Trace “animal” and “robot” side by side',
        summary: 'Run both prompts through tokenization, then predict and verify downstream effects where the tools expose evidence. Record unknowns honestly.',
        prompt: 'For every row, what entered, what changed it, what left, and how do you know?',
        takeaway: 'Dependencies can be predicted structurally even when exact model values require execution.',
        presenterCue: 'Reject both extremes: “everything definitely changes” and “nothing can be said without running it.”',
      }),
      teachingMoment({
        id: 'capstone/debrief',
        kind: 'debrief',
        eyebrow: 'A usable mental model',
        title: 'Runtime representations change; learned weights remain fixed',
        summary: 'Text, tokenization, initial states, contextual states, logits, probabilities, cache contents, and output may change. Ordinary inference does not update model parameters.',
        takeaway: 'Trace the representation, locate the operation, identify the controller, and state the strength of the evidence.',
        presenterCue: 'Finish by having the learner narrate the whole pipeline without collapsing tokens, vectors, states, scores, and selected outputs.',
      }),
    ],
  },
} satisfies Record<LlmCourseLessonId, LessonTeachingMoments>;
