import type { LabNarrative } from '../types';

export const agentNarratives: LabNarrative[] = [
  {
    id: 'agent-loop', chapter: 'Agent runtime · 1 of 7',
    hookTitle: 'What turns one model response into an agent?',
    hookCopy: 'A model can propose text or structured tool calls. A harness makes the system agentic by repeatedly assembling context, invoking the model, validating and executing tools, and returning observations until a stop condition is reached.',
    hookPrompt: 'When a tool runs, which part actually caused the side effect?',
    mechanismTitle: 'The model chooses the next proposal; deterministic code owns the loop.',
    mechanismSteps: [
      { label: 'Assemble', expression: 'Select useful evidence', copy: 'The harness selects messages, tools, and environment evidence.' },
      { label: 'Infer', expression: 'Ask for the next proposal', copy: 'The model returns text, a tool proposal, or structured output.' },
      { label: 'Act', expression: 'Check, then perform', copy: 'Application code checks and performs the allowed operation.' },
      { label: 'Repeat', expression: 'Continue until done or limited', copy: 'The result becomes an observation for the next model call.' },
    ],
    mechanismConclusion: 'Agency emerges from the model-harness-environment loop, not from a special “agent” neuron inside the model.',
    exerciseTitle: 'Exercise 1 — step through an agent run.', duration: '8–10 minutes',
    tasks: ['Separate model decisions from harness operations.', 'Inject a tool failure and follow the recovery turn.', 'Identify the exact stop condition in the successful trace.'],
    returnQuestion: 'Which boundaries remain deterministic even when the model output varies?',
    takeaway: 'An agent is a model embedded in a controlled loop with tools and state.',
    limitation: 'A trace shows observable decisions and effects, not private chain-of-thought or guaranteed competence.',
    bridge: 'Every model turn depends on the context the harness chooses to assemble.',
    hookNotes: 'Use the ccunpacked.dev 11-stage loop as orientation, then collapse it to assemble → infer → act → observe → repeat.',
    mechanismNotes: 'Keep model and harness visually separate. The model proposes; code executes.',
    exerciseNotes: 'Ask participants to name the owner of each step before advancing.',
    debriefNotes: 'Compare a chatbot’s single response with the same model inside a multi-turn tool loop.',
  },
  {
    id: 'subagents', chapter: 'Agent runtime · 2 of 7',
    hookTitle: 'When does more than one agent make the work faster rather than messier?',
    hookCopy: 'Subagents move bounded investigation or implementation into separate contexts. Parallelism can reduce elapsed time and parent-context noise, but it adds token cost, synthesis work, and shared-write risk.',
    hookPrompt: 'What must be isolated: conversation context, filesystem writes, or both?',
    mechanismTitle: 'Delegate bounded tasks; return evidence to one accountable parent.',
    mechanismSteps: [
      { label: 'Partition', expression: 'Split into bounded outcomes', copy: 'Choose independent deliverables with explicit inputs and outputs.' },
      { label: 'Isolate', expression: 'Give only needed context', copy: 'Each child receives only the context needed for its task.' },
      { label: 'Execute', expression: 'Overlap independent work', copy: 'Independent work can reduce wall-clock time while total compute remains.' },
      { label: 'Synthesize', expression: 'Review all returned evidence', copy: 'The parent reviews evidence, resolves conflicts, and owns the final result.' },
    ],
    mechanismConclusion: 'Concurrency is an orchestration choice, not free intelligence; isolation and verification determine whether it helps.',
    exerciseTitle: 'Exercise 2 — coordinate three subagents.', duration: '8–10 minutes',
    tasks: ['Compare sequential and parallel elapsed time.', 'Create an overlapping edit and observe the collision.', 'Enable worktree isolation and explain why a merge is still required.'],
    returnQuestion: 'Which tasks are independent enough to parallelize, and who verifies their combined result?',
    takeaway: 'Subagents trade more total compute and coordination for lower elapsed time and cleaner parent context.',
    limitation: 'Separate contexts do not automatically isolate shared files, credentials, services, or other external state.',
    bridge: 'Every parent and child still depends on the context assembled for its next model call.',
    hookNotes: 'Ask the room to predict whether parallelism reduces time, tokens, or both before revealing the metrics.',
    mechanismNotes: 'Keep context isolation and filesystem isolation visually separate.',
    exerciseNotes: 'Use the overlapping-edit scenario to show why “different agent” does not mean “different workspace.”',
    debriefNotes: 'End by identifying one task that should remain with the parent because it requires global synthesis.',
  },
  {
    id: 'context-harness', chapter: 'Agent context · 3 of 7',
    hookTitle: 'What does the model know if the harness does not put it in context?',
    hookCopy: 'Repositories, browser tabs, memory files, tool registries, and earlier sessions live outside the model. The harness decides what to retrieve, serialize, compact, order, and omit for each inference call.',
    hookPrompt: 'Is an omitted tool result forgotten—or merely absent from this call?',
    mechanismTitle: 'Context engineering is selection under a finite budget.',
    mechanismSteps: [
      { label: 'Collect', expression: 'Find candidate evidence', copy: 'Candidate context comes from several external systems.' },
      { label: 'Prioritize', expression: 'Required, relevant, then recent', copy: 'Stable rules and the current goal outrank incidental history.' },
      { label: 'Compact', expression: 'Shorten with visible trade-offs', copy: 'Summaries save space while sacrificing exact detail.' },
      { label: 'Serialize', expression: 'Order the next model input', copy: 'Ordering and role labels shape the model’s available evidence.' },
    ],
    mechanismConclusion: 'The context window is working memory for one call; files, databases, and traces provide external persistence.',
    exerciseTitle: 'Exercise 3 — trace a context lifecycle.', duration: '10–12 minutes',
    tasks: ['Tighten the budget and observe what disappears first.', 'Compare a continued turn, compaction, model switch, and resumed session.', 'Explain why prompt caching is neither memory nor context persistence.'],
    returnQuestion: 'Which information must survive every budget, and which can be retrieved on demand?',
    takeaway: 'Harness quality depends on giving the model the smallest sufficient context.',
    limitation: 'Token counts are model-specific, and summaries can silently remove evidence needed by a later step.',
    bridge: 'Context may describe a tool, but policy still controls whether its proposed call can execute.',
    hookNotes: 'Emphasize that “memory” is overloaded: context, KV cache, files, and learned weights are different mechanisms.',
    mechanismNotes: 'Use compaction and structured handoffs as different external-state strategies, not magic unlimited memory.',
    exerciseNotes: 'Ask the room to defend one excluded segment before increasing the budget.',
    debriefNotes: 'Connect progressive tool discovery to lower context cost and clearer tool selection.',
  },
  {
    id: 'memory-instructions', chapter: 'Agent context · 4 of 7',
    hookTitle: 'Where should an agent put something that must matter tomorrow?',
    hookCopy: 'Active context, project instructions, learned memory, reusable skills, files, databases, and secret stores have different lifetimes and authority. Treating them all as “memory” hides important engineering decisions.',
    hookPrompt: 'Should “always run the tests” be remembered, instructed, or enforced?',
    mechanismTitle: 'Place information by lifetime, authority, fidelity, and sensitivity.',
    mechanismSteps: [
      { label: 'Classify', expression: 'Temporary or durable?', copy: 'Decide whether the information serves this task or future work.' },
      { label: 'Authorize', expression: 'Preference is not policy', copy: 'Personal memory cannot replace required repository instructions.' },
      { label: 'Preserve', expression: 'Summary is not the source', copy: 'Exact evidence stays in retrievable external state with provenance.' },
      { label: 'Protect', expression: 'Keep secrets out of prompts', copy: 'Credentials are resolved at execution time, not stored in model context.' },
    ],
    mechanismConclusion: 'Durable rules should be explicit; learned memory should be inspectable; exact evidence should remain externally retrievable.',
    exerciseTitle: 'Exercise 4 — place six kinds of information.', duration: '8–10 minutes',
    tasks: ['Place a team rule, user preference, and reusable workflow.', 'Keep exact audit evidence outside lossy memory.', 'Reject a credential from every prompt-visible destination.'],
    returnQuestion: 'Which facts may be summarized, which must be versioned, and which must never enter model context?',
    takeaway: 'Instructions, memory, skills, external state, and secrets solve different persistence problems.',
    limitation: 'Memory can be stale, incomplete, or incorrectly inferred; users need visibility and control.',
    bridge: 'When guidance must run deterministically at a lifecycle event, use a hook rather than relying on recall.',
    hookNotes: 'Start with the API-token card because its wrong destinations are immediately consequential.',
    mechanismNotes: 'Compare AGENTS.md and CLAUDE.md without implying they are identical implementations.',
    exerciseNotes: 'Ask participants to add enforcement for one explicit instruction after placing it.',
    debriefNotes: 'Separate the source of truth from the small slice retrieved into a model call.',
  },
  {
    id: 'hooks-lifecycle', chapter: 'Agent safety · 5 of 7',
    hookTitle: 'How can deterministic code intervene inside a probabilistic agent loop?',
    hookCopy: 'Hooks attach commands or handlers to lifecycle events such as prompt submission, tool use, compaction, subagent execution, and stopping. The event determines which evidence exists and whether an effect can still be prevented.',
    hookPrompt: 'Is PostToolUse too late to protect a file from being written?',
    mechanismTitle: 'Choose the earliest event with enough evidence and control.',
    mechanismSteps: [
      { label: 'Observe', expression: 'Read the event payload', copy: 'A lifecycle event exposes structured information about the pending transition.' },
      { label: 'Evaluate', expression: 'Apply deterministic rules', copy: 'Deterministic logic logs, validates, blocks, or transforms behavior.' },
      { label: 'Return', expression: 'Allow, deny, or explain', copy: 'The harness applies the handler result before continuing the loop.' },
      { label: 'Audit', expression: 'Record what happened', copy: 'Record hook execution and its effect for diagnosis and evaluation.' },
    ],
    mechanismConclusion: 'A hook is lifecycle automation; permissions and sandboxing remain separate enforcement layers.',
    exerciseTitle: 'Exercise 5 — place four lifecycle hooks.', duration: '8–10 minutes',
    tasks: ['Block a protected write before execution.', 'Format code only after an edit succeeds.', 'Restore context after compaction and validate tests before stopping.'],
    returnQuestion: 'What is the earliest event that has both the necessary evidence and the ability to intervene?',
    takeaway: 'Hooks make selected lifecycle behavior deterministic, observable, and repeatable.',
    limitation: 'A hook covers only the events and tool paths the harness exposes; it is not a universal security boundary.',
    bridge: 'Hooks can intercept proposals, but the final capability boundary still needs validation, permissions, and isolation.',
    hookNotes: 'Move left-to-right across the event timeline and ask what information exists at each point.',
    mechanismNotes: 'Make “before effect” and “after effect” visually unambiguous.',
    exerciseNotes: 'Let participants choose a wrong late event before revealing the earliest useful one.',
    debriefNotes: 'Compare an advisory instruction, an intercepting hook, an authorization rule, and an OS sandbox.',
  },
  {
    id: 'tool-boundaries', chapter: 'Agent safety · 6 of 7',
    hookTitle: 'If the model can name an action, does that mean it can perform it?',
    hookCopy: 'A tool call is structured model output. Reliable harnesses validate its schema, authenticate the caller, authorize the effect, request approval when needed, execute in a bounded environment, and record the outcome.',
    hookPrompt: 'Can a system prompt enforce a permission boundary?',
    mechanismTitle: 'Proposal passes through code before it becomes an effect.',
    mechanismSteps: [
      { label: 'Parse', expression: 'Identify action and inputs', copy: 'Structured output identifies the proposed capability and inputs.' },
      { label: 'Validate', expression: 'Reject malformed inputs', copy: 'Types and required fields fail closed before execution.' },
      { label: 'Authorize', expression: 'Check identity, scope, and risk', copy: 'Identity, scope, and risk determine allow, approval, or deny.' },
      { label: 'Observe', expression: 'Compare proposal with outcome', copy: 'The harness records both the proposal and what actually changed.' },
    ],
    mechanismConclusion: 'Prompts influence behavior; deterministic boundaries control capability.',
    exerciseTitle: 'Exercise 6 — gate four tool calls.', duration: '8–10 minutes',
    tasks: ['Compare a read, write, and destructive proposal.', 'Approve one simulated write under strict policy.', 'Show that malformed arguments fail before permission policy.'],
    returnQuestion: 'Which evidence proves success: the model’s final sentence or the environment outcome?',
    takeaway: 'Schemas, permissions, approvals, sandboxes, and outcome checks make tool use governable.',
    limitation: 'No single guardrail is sufficient; authorization, isolation, monitoring, and evaluation must work together.',
    bridge: 'Close the loop by evaluating traces and real outcomes, not only fluent final answers.',
    hookNotes: 'Ask whether “I deleted the file” proves deletion. Use the answer to distinguish transcript from outcome.',
    mechanismNotes: 'Place schema validation before permissions and permissions before side effects.',
    exerciseNotes: 'Keep all effects simulated; the lesson is the boundary sequence.',
    debriefNotes: 'End on the harness principle: capabilities should be explicit, least-privileged, observable, and interruptible.',
  },
  {
    id: 'agent-evals', chapter: 'Agent evaluation · 7 of 7',
    hookTitle: 'Does one successful agent demo prove the system is reliable?',
    hookCopy: 'Agent behavior varies across attempts, tasks, tool observations, and environment states. Evaluation turns that variability into evidence by repeating well-specified tasks and grading both the trace and the observable final state.',
    hookPrompt: 'Would you trust an agent that succeeds once in three attempts if the successful transcript looks excellent?',
    mechanismTitle: 'Define the task, repeat trials, grade evidence, then inspect failures.',
    mechanismSteps: [
      { label: 'Specify', expression: 'Define success and non-goals', copy: 'State what must change and what must remain unchanged.' },
      { label: 'Repeat', expression: 'Run multiple independent trials', copy: 'Sample nondeterministic behavior across multiple independent runs.' },
      { label: 'Grade', expression: 'Combine suitable graders', copy: 'Match deterministic, rubric-based, and calibration graders to the evidence.' },
      { label: 'Diagnose', expression: 'Read the trace behind the score', copy: 'Read transcripts and outcomes before treating a metric as trustworthy.' },
    ],
    mechanismConclusion: 'The score summarizes a suite; the trace and environment outcome explain whether the score deserves trust.',
    exerciseTitle: 'Exercise 7 — run and diagnose an agent evaluation.', duration: '10–12 minutes',
    tasks: ['Compare focused and critique-loop prompts across 20 trials.', 'Separate pass@3 from pass³ and explain the reliability difference.', 'Open one failed trace and identify whether the task, agent, or grader is wrong.'],
    returnQuestion: 'Did the change improve capability, consistency, cost, latency—or only the best-looking response?',
    takeaway: 'Reliable agent engineering starts with repeated tasks, observable outcomes, calibrated graders, and trace inspection.',
    limitation: 'A seeded teaching suite demonstrates evaluation mechanics; it is not evidence about a real model or production task distribution.',
    bridge: 'Use the resulting failure set to decide which prompt, tool, policy, or architecture change should be implemented next.',
    hookNotes: 'Ask for a show of hands after “one in three.” Then distinguish the chance of at least one success from the chance that every attempt succeeds.',
    mechanismNotes: 'Keep task, trial, trace, outcome, and grader as separate nouns. Most evaluation confusion comes from collapsing them.',
    exerciseNotes: 'Have participants optimize one metric and narrate what becomes worse. Do not accept “the score increased” without naming the score.',
    debriefNotes: 'End by opening a failed trace. A dashboard without transcript and outcome review can create precise-looking false confidence.',
  },
];
