import type { LabNarrative } from '../types';

export const languageNarratives: LabNarrative[] = [
  {
    id: 'tokenization',
    chapter: 'Language inference · 1 of 5',
    hookTitle: 'The model never sees the sentence you typed.',
    hookCopy: 'Before a transformer can predict anything, a tokenizer turns text into a sequence of vocabulary IDs. Spaces, punctuation, and unusual words can all change the sequence.',
    hookPrompt: 'Will adding one character always add one token?',
    mechanismTitle: 'One string becomes pieces, IDs, bytes, and context slots.',
    mechanismSteps: [
      { label: 'Text', expression: '"unbelievable!"', copy: 'Start with characters a human can read.' },
      { label: 'Pieces', expression: '["un", "believ", "able", "!"]', copy: 'The tokenizer applies its vocabulary and merge rules.' },
      { label: 'IDs', expression: '[359, 9912, 481, 0]', copy: 'The model receives integer lookup keys, not words.' },
      { label: 'Budget', expression: '4 context slots', copy: 'Every resulting token consumes room in the context window.' },
    ],
    mechanismConclusion: 'Tokenization is a learned compression scheme for text—not a linguistic truth about where words begin or end.',
    exerciseTitle: 'Exercise 1 — reveal exactly what the model receives.',
    duration: '8–10 minutes',
    tasks: ['Predict how punctuation will change the pieces.', 'Inspect a token’s ID, bytes, and character count.', 'Compare the guided tokenizer with Bonsai’s exact base tokenizer and runtime count.'],
    returnQuestion: 'Which edit produced the least intuitive token boundary?',
    takeaway: 'The first representation is discrete: an ordered sequence of token IDs.',
    limitation: 'Nearby IDs do not imply similar meanings, and the guided tokenizer is not Bonsai output.',
    bridge: 'Once tokens have vectors, attention decides which positions exchange information.',
    hookNotes: 'Ask participants to predict the effect of appending an exclamation mark before showing any token boundaries.',
    mechanismNotes: 'Stress the separation between visible token text, token ID, UTF-8 bytes, and the eventual learned embedding vector.',
    exerciseNotes: 'Keep one pair on guided mode and another on Bonsai mode, then compare what was inspectable in each.',
    debriefNotes: 'Ask why the exact same semantic sentence can consume different context in another language or tokenizer.',
  },
  {
    id: 'attention',
    chapter: 'Language inference · 2 of 5',
    hookTitle: 'When “tired” updates, which earlier token should it consult?',
    hookCopy: 'A transformer does not read the whole sentence into one fixed state. Each position builds a query and uses it to gather a weighted mixture of information from allowed positions.',
    hookPrompt: 'In “The animal was tired,” should “tired” gather more from “animal” or “was”?',
    mechanismTitle: 'Queries ask, keys match, values carry the information.',
    mechanismSteps: [
      { label: 'Project', expression: 'Q = XWQ · K = XWK · V = XWV', copy: 'The same input creates three role-specific views.' },
      { label: 'Compare', expression: 'S = QKᵀ / √d', copy: 'Dot products score every allowed query-key pair.' },
      { label: 'Constrain', expression: 'A = softmax(mask(S))', copy: 'The causal mask blocks future tokens; each row becomes weights.' },
      { label: 'Gather', expression: 'O = AV', copy: 'Each output is a weighted mixture of value vectors.' },
    ],
    mechanismConclusion: 'Attention changes a token representation by routing information between positions; it does not choose the final next token by itself.',
    exerciseTitle: 'Exercise 2 — trace one exact attention head.',
    duration: '10–12 minutes',
    tasks: ['Follow X through Q, K, V, scores, mask, softmax, and output.', 'Predict the dominant source for “tired.”', 'Disable the causal mask and explain why the result is invalid for generation.'],
    returnQuestion: 'Which operation changed similarity scores into a usable mixture?',
    takeaway: 'Attention is content-dependent information routing across token positions.',
    limitation: 'A bright attention cell is a strong weight, not proof of a human-readable reasoning step.',
    bridge: 'The final representation is converted into scores for every possible next token.',
    hookNotes: 'Let the room vote between “animal” and “was.” The lab will make the answer numerical.',
    mechanismNotes: 'Use the database analogy only briefly; learned keys and queries need not behave like human-designed lookup fields.',
    exerciseNotes: 'Have participants narrate one row aloud: allowed columns, score, normalized weight, and value contribution.',
    debriefNotes: 'Ask what multiple heads add: parallel relationships, not eleven copies of the same explanation.',
  },
  {
    id: 'next-token',
    chapter: 'Language inference · 4 of 5',
    hookTitle: 'If “Paris” is most likely, why would a model ever choose something else?',
    hookCopy: 'A language model produces a distribution, not a single word. Decoding turns that distribution into one token, while training asks how much probability the model assigned to the token that actually followed.',
    hookPrompt: 'Should a creative model always choose rank one?',
    mechanismTitle: 'Logits become a distribution, then a choice, then a new context.',
    mechanismSteps: [
      { label: 'Score', expression: 'logits ∈ ℝ|V|', copy: 'One score is produced for every vocabulary token.' },
      { label: 'Temper', expression: 'zᵢ / T', copy: 'Temperature changes relative confidence before normalization.' },
      { label: 'Normalize', expression: 'pᵢ = softmax(z/T)', copy: 'Probabilities become non-negative and sum to one.' },
      { label: 'Learn', expression: 'L = −ln(pcorrect)', copy: 'Low confidence in the observed token creates a large penalty.' },
    ],
    mechanismConclusion: 'Generation and training meet at the same distribution: decoding samples from it; cross-entropy evaluates it.',
    exerciseTitle: 'Exercise 4 — turn probabilities into a token and a loss.',
    duration: '8–10 minutes',
    tasks: ['Compare greedy decoding with seeded sampling.', 'Raise temperature and describe what happens to the distribution.', 'Change the expected token and explain the cross-entropy response in guided and live modes.'],
    returnQuestion: 'What changed when temperature moved—the ranking, the certainty, or both?',
    takeaway: 'Text generation is a repeated probability-driven decision over the vocabulary.',
    limitation: 'A probability distribution describes the next local choice; it is not a calibrated measure of truth or understanding.',
    bridge: 'Every chosen token extends the sequence—and makes reuse of earlier computation increasingly valuable.',
    hookNotes: 'Ask for examples where rank-one decoding sounds repetitive. Then distinguish diversity from randomness without control.',
    mechanismNotes: 'Connect the loss formula to the probability bars: the entire loss for one target can be read from one bar.',
    exerciseNotes: 'Require the same random seed when comparing temperatures so the comparison remains interpretable.',
    debriefNotes: 'Ask why a plausible but incorrect token can still have high probability and what that means for factuality.',
  },
  {
    id: 'kv-cache',
    chapter: 'Language inference · 5 of 5',
    hookTitle: 'Why does a longer conversation become a memory problem one token at a time?',
    hookCopy: 'Autoregressive decoding repeatedly attends to the same earlier positions. Caching their keys and values avoids recomputing them, but keeps a growing tensor in memory for every layer.',
    hookPrompt: 'Why cache keys and values, but not every old query?',
    mechanismTitle: 'Reuse earlier K and V; compute only the newest row.',
    mechanismSteps: [
      { label: 'Prefill', expression: 'K₁…ₙ, V₁…ₙ', copy: 'The prompt creates keys and values at every layer.' },
      { label: 'Store', expression: '[layer, KV head, token, head dim]', copy: 'The cache retains tensors needed by future tokens.' },
      { label: 'Append', expression: 'Kₙ₊₁, Vₙ₊₁', copy: 'A new token adds one row per layer and KV head.' },
      { label: 'Attend', expression: 'Qₙ₊₁K₁…ₙ₊₁ᵀ', copy: 'Only the current query needs the full history.' },
    ],
    mechanismConclusion: 'Cache memory grows linearly with context length, layer count, KV heads, head dimension, and bytes per value.',
    exerciseTitle: 'Exercise 5 — make context memory visible.',
    duration: '8–10 minutes',
    tasks: ['Double context length and predict the memory change.', 'Compare MHA, GQA, and MQA with the same model shape.', 'Explain why queries are transient while keys and values are reused.'],
    returnQuestion: 'Which architectural change reduced memory without shortening context?',
    takeaway: 'The KV cache trades memory for faster autoregressive decoding.',
    limitation: 'KV cache is inference state, not long-term semantic memory, and it does not remove the cost of attending over the context.',
    bridge: 'Not every AI vector belongs inside the generation pipeline; embeddings form a separate semantic system.',
    hookNotes: 'Let participants estimate whether doubling context doubles or quadruples cache memory before touching the controls.',
    mechanismNotes: 'Separate prefill compute, decode compute, and cache memory. They scale differently and are often conflated.',
    exerciseNotes: 'Ask one group to optimize memory using architecture and another using numerical precision, then compare tradeoffs.',
    debriefNotes: 'Return to the query question: an old query answered an old position; its K and V can still serve future positions.',
  },
];
