import type { LabNarrative } from '../types';

export const learningNarratives: LabNarrative[] = [
  {
    id: 'perceptron',
    chapter: 'Neural and vision · 1 of 6',
    hookTitle: 'How did one weighted sum become the atom of modern AI?',
    hookCopy: 'Rosenblatt’s perceptron turned inputs into a score and adjusted its weights after mistakes. The rule is tiny; networks built from related units now contain billions of learned parameters.',
    hookPrompt: 'Can the same single line learn both OR and XOR?',
    mechanismTitle: 'Predict, compare, and move the weights only after a mistake.',
    mechanismSteps: [
      { label: 'Score', expression: 's = w·x + b', copy: 'Inputs are multiplied by weights and added with bias.' },
      { label: 'Decide', expression: 'ŷ = sign(s)', copy: 'The sign places the example on one side of a boundary.' },
      { label: 'Compare', expression: 'ŷ ?= y', copy: 'A correct prediction leaves the parameters unchanged.' },
      { label: 'Update', expression: 'w ← w + ηyx', copy: 'A mistake turns the example into a movement direction.' },
    ],
    mechanismConclusion: 'If a linear boundary exists, repeated local corrections can find it.',
    exerciseTitle: 'Exercise 7 — teach one artificial neuron.',
    duration: '8–10 minutes',
    tasks: ['Step through OR and narrate one weight update.', 'Relate the score equation to the visible decision boundary.', 'Switch to XOR and diagnose why training cannot converge.'],
    returnQuestion: 'Did XOR fail because the update rule was weak—or because no separating line exists?',
    takeaway: 'A perceptron learns a linear decision boundary from mistakes.',
    limitation: 'A single boundary cannot represent XOR, and its hard step activation has no useful gradient for multilayer learning.',
    bridge: 'Gradient descent generalizes the idea of using error to choose a parameter direction.',
    hookNotes: 'Frame XOR failure as useful evidence. A model limitation can reveal exactly what the next idea must provide.',
    mechanismNotes: 'Keep the physical dial metaphor: positive target turns active inputs up; negative target turns them down.',
    exerciseNotes: 'Ask participants to predict the update before pressing Step. The point is the rule, not racing to convergence.',
    debriefNotes: 'Use the failed XOR run to motivate both a smoother learning signal and multiple composed boundaries.',
  },
  {
    id: 'gradient-descent',
    chapter: 'Neural and vision · 2 of 6',
    hookTitle: 'Why did the “local valley” picture almost make neural learning look impossible?',
    hookCopy: 'Gradient descent starts from current parameters and follows local slopes toward lower loss. A two-dimensional landscape makes the rule visible—but can also hide what high-dimensional models are really like.',
    hookPrompt: 'Does the gradient point downhill or uphill?',
    mechanismTitle: 'Loss supplies the destination; derivatives supply the local direction.',
    mechanismSteps: [
      { label: 'Predict', expression: 'ŷᵢ = wxᵢ + b', copy: 'Current parameters produce one output per sample.' },
      { label: 'Measure', expression: 'L = mean((ŷ−y)²)', copy: 'Residuals become one scalar objective.' },
      { label: 'Differentiate', expression: '∇L = [∂L/∂w, ∂L/∂b]', copy: 'Each component is a local uphill slope.' },
      { label: 'Update', expression: 'θ ← θ − η∇L', copy: 'Subtracting the gradient moves parameters downhill.' },
    ],
    mechanismConclusion: 'The learning rate controls how far—not which direction—the local gradient asks us to move.',
    exerciseTitle: 'Exercise 8 — walk downhill yourself.',
    duration: '8–10 minutes',
    tasks: ['Take one useful step and explain both update signs.', 'Compare analytic gradients with finite differences.', 'Run the unstable learning rate and diagnose the growing loss.'],
    returnQuestion: 'Why does subtracting a negative gradient increase a parameter?',
    takeaway: 'A gradient stores one local slope for every trainable parameter.',
    limitation: 'Our convex two-parameter surface is an inspectable slice, not the full geometry of a large model.',
    bridge: 'Backpropagation computes those parameter slopes efficiently through a composed network.',
    hookNotes: 'Correct the common shorthand immediately: the gradient points uphill; descent subtracts it.',
    mechanismNotes: 'Tie finite differences to the visual slope before introducing analytic derivatives.',
    exerciseNotes: 'On return, compare inefficient learning with unstable learning; only one moves in the wrong practical regime.',
    debriefNotes: 'Ask why testing every possible parameter combination is impossible once the model has billions of dimensions.',
  },
  {
    id: 'backpropagation',
    chapter: 'Neural and vision · 3 of 6',
    hookTitle: 'How can one wrong prediction assign responsibility to every parameter?',
    hookCopy: 'Backpropagation treats a network as a graph of small operations. The forward pass records values; the backward pass combines local derivatives with the gradient arriving from downstream.',
    hookPrompt: 'Does each node need to understand the whole network?',
    mechanismTitle: 'Forward computes values. Backward computes responsibility.',
    mechanismSteps: [
      { label: 'Forward', expression: 'x → z₁ → ReLU → z₂ → p', copy: 'Each operation stores the values needed later.' },
      { label: 'Loss', expression: 'L = BCE(p,y)', copy: 'One scalar becomes the starting point for every gradient.' },
      { label: 'Chain', expression: 'dL/dz = upstream × local', copy: 'Each node needs only two small pieces of information.' },
      { label: 'Update', expression: 'θ ← θ − η dL/dθ', copy: 'Every parameter receives its own share of the signal.' },
    ],
    mechanismConclusion: 'Backpropagation is organized bookkeeping for the chain rule, reused across an arbitrarily large graph.',
    exerciseTitle: 'Exercise 9 — make every gradient accountable.',
    duration: '10–12 minutes',
    tasks: ['Trace the active ReLU forward and backward passes.', 'Match analytic gradients with finite differences.', 'Switch ReLU off and identify which parameters stop receiving gradient.'],
    returnQuestion: 'Why does the output bias still learn when the hidden ReLU is inactive?',
    takeaway: 'Local derivatives compose into gradients for distant parameters.',
    limitation: 'An inactive ReLU blocks only paths upstream of that unit for that example—not necessarily the entire network.',
    bridge: 'With gradients available across layers, depth can learn new intermediate representations.',
    hookNotes: 'Use the word responsibility, then replace the metaphor with the exact derivative at each node.',
    mechanismNotes: 'Point both directions: values flow right in the forward pass; gradients flow left in the backward pass.',
    exerciseNotes: 'Require participants to explain one row of the gradient table, including the numerical check.',
    debriefNotes: 'Ask why a modular local rule scales better than deriving a new global formula for every architecture.',
  },
  {
    id: 'depth',
    chapter: 'Neural and vision · 4 of 6',
    hookTitle: 'XOR defeats one line—but not a change of coordinates.',
    hookCopy: 'Matching labels sit on opposite corners of the input plane. A hidden layer can create new features that rearrange those four examples into a space where a simple boundary works.',
    hookPrompt: 'What should the first layer compute so XOR becomes easy?',
    mechanismTitle: 'The first layer changes the representation; the second makes the decision.',
    mechanismSteps: [
      { label: 'Input', expression: '[x₁, x₂]', copy: 'The diagonal positive examples are not linearly separable.' },
      { label: 'Feature 1', expression: 'hOR = step(x₁+x₂−0.5)', copy: 'One hidden unit detects whether either input is active.' },
      { label: 'Feature 2', expression: 'hAND = step(x₁+x₂−1.5)', copy: 'Another detects the exceptional both-active case.' },
      { label: 'Output', expression: 'step(hOR−2hAND−0.5)', copy: 'One line now separates the hidden coordinates.' },
    ],
    mechanismConclusion: 'Depth composes functions so later layers receive learned features instead of only raw inputs.',
    exerciseTitle: 'Exercise 10 — make XOR linearly separable.',
    duration: '8–10 minutes',
    tasks: ['Confirm one boundary leaves at least one mistake.', 'Inspect hOR and hAND for all four inputs.', 'Explain why a line works after the representation changes.'],
    returnQuestion: 'Did the output rule become more complicated—or did its input become better?',
    takeaway: 'Depth can make a difficult geometry simple by composing intermediate features.',
    limitation: 'The XOR features are handcrafted hard steps; real networks normally learn differentiable features from data.',
    bridge: 'Convolution brings the same composition idea to local patterns in images.',
    hookNotes: 'Invite someone to draw a separating line before revealing the hidden coordinates.',
    mechanismNotes: 'Keep the language geometric: points move in representation space even though the original inputs do not change.',
    exerciseNotes: 'Have participants explain XOR using hOR and hAND, not only repeat the truth table.',
    debriefNotes: 'Ask how many useful features a real layer might learn and why later layers do not need to rediscover raw pixels.',
  },
];
