import type { LabNarrative } from '../types';

export const visionNarratives: LabNarrative[] = [
  {
    id: 'convolution',
    chapter: 'Neural and vision · 5 of 6',
    hookTitle: 'How can one tiny detector search an entire image?',
    hookCopy: 'A convolution reuses the same kernel at every location. Each output activation answers one local question: how strongly does this image patch match the learned pattern?',
    hookPrompt: 'Should moving the pattern require learning a new set of weights?',
    mechanismTitle: 'Nine products produce one activation; sliding produces a map.',
    mechanismSteps: [
      { label: 'Select', expression: 'patch = X[r:r+3, c:c+3]', copy: 'Choose the local pixels beneath the kernel.' },
      { label: 'Multiply', expression: 'patch ⊙ kernel', copy: 'Pair each pixel with the corresponding shared weight.' },
      { label: 'Reduce', expression: 'a[r,c] = Σ products + b', copy: 'Nine contributions collapse to one number.' },
      { label: 'Slide', expression: '(r,c) → activation map', copy: 'Repeat the same calculation across the image.' },
    ],
    mechanismConclusion: 'Weight sharing lets one learned feature detector respond wherever its pattern appears.',
    exerciseTitle: 'Exercise 11 — slide a visual filter.',
    duration: '8–10 minutes',
    tasks: ['Select an output cell and locate its exact input patch.', 'Verify the nine products and their sum.', 'Edit or replace the kernel and predict how the activation map will change.'],
    returnQuestion: 'Which changed globally when one kernel weight changed—and why?',
    takeaway: 'Convolution creates spatial feature maps with local connectivity and shared parameters.',
    limitation: 'One bright activation reports a pattern match, not object understanding; deeper layers must compose local evidence.',
    bridge: 'The Digit CNN stacks these maps, reduces them, and converts the result into class evidence.',
    hookNotes: 'Use a moved edge or corner to make the weight-sharing question concrete.',
    mechanismNotes: 'Follow one selected cell all the way back to its source patch; avoid jumping straight to the whole activation map.',
    exerciseNotes: 'Ask participants to predict the sign of the sum before reading the trace total.',
    debriefNotes: 'Connect translation behavior to the same kernel being reused, while noting that pooling and boundaries complicate perfect invariance.',
  },
  {
    id: 'digits',
    chapter: 'Neural and vision · 6 of 6',
    hookTitle: 'What do nine thousand learned numbers see in your drawing?',
    hookCopy: 'A small convolutional network turns pixels into activation maps, reduces their spatial size, and accumulates evidence for ten output classes—all locally in the browser.',
    hookPrompt: 'Which layer should be easiest for a human to interpret?',
    mechanismTitle: 'Local patterns become feature maps, then class evidence.',
    mechanismSteps: [
      { label: 'Pixels', expression: '1 × 28 × 28', copy: 'The drawing becomes normalized grayscale values.' },
      { label: 'Conv + pool', expression: '8 × 14 × 14', copy: 'Early filters detect reusable local structure.' },
      { label: 'Conv + pool', expression: '16 × 7 × 7', copy: 'Later maps combine patterns over larger regions.' },
      { label: 'Classify', expression: '784 → 10 logits → softmax', copy: 'A dense layer turns accumulated evidence into probabilities.' },
    ],
    mechanismConclusion: 'The prediction is the final stage of a representation pipeline, not a direct comparison with stored pictures.',
    exerciseTitle: 'Exercise 12 — recognize a handwritten digit.',
    duration: '10–12 minutes',
    tasks: ['Run two deterministic samples and compare confidence.', 'Draw or erase one stroke, predict the change, then run inference.', 'Inspect early and late activation maps and describe what becomes harder to name.'],
    returnQuestion: 'Which perturbation changed the prediction most, and where did its effect first appear?',
    takeaway: 'Learned filters compose local evidence into a ten-class prediction.',
    limitation: 'High confidence is not certainty, and a digit-trained network does not gain general visual understanding.',
    bridge: 'Return to the full loop: representations enable predictions; loss and gradients shape the representations.',
    hookNotes: 'Ask why early-layer maps often look more interpretable than late-layer maps before opening the activation inspector.',
    mechanismNotes: 'Keep tensor dimensions visible so “deeper” does not become a vague synonym for “smarter.”',
    exerciseNotes: 'Use one clean sample and one deliberately awkward drawing so confidence and distribution shift become discussable.',
    debriefNotes: 'Close by asking where token, attention, gradient, and convolution representations differ—and what unifies them.',
  },
];
